### ISSUE TITLE
Error from TEI to JATS

### ISSUE THREAD

**Issue by marcbria** [elifesciences/metypeset-docker#9]
Hi,

First thanks for the initiative of dockerizing meTypeset.

I discovered the project and I tried today to convert a simple TEI to JATS.

But, when I call it, I got this error:
```
$ docker run --rm -t -i -v"$(pwd):/data" elifesciences/metypeset   python bin/meTypeset.py docx /data/2207-10752-3-PB.pdf  /data/output
Traceback (most recent call last):
  File "bin/meTypeset.py", line 257, in <module>
    main()
  File "bin/meTypeset.py", line 253, in main
    me_typeset_instance.run()
  File "bin/meTypeset.py", line 245, in run
    self.run_modules()
  File "bin/meTypeset.py", line 152, in run_modules
    DocxToTei(self.gv).run(True, self.args['--proprietary'])
  File "/opt/meTypeset/bin/docxtotei.py", line 128, in run
    with zipfile.ZipFile(self.gv.input_file_path, "r") as z:
  File "/usr/local/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

So, zipped the XML and the error changes but is not still working:

```
$ sudo docker run --rm -t -i -v"$(pwd):/data" elifesciences/metypeset   python bin/meTypeset.py docx /data/a.zip  /data/output
Traceback (most recent call last):
  File "bin/meTypeset.py", line 257, in <module>
    main()
  File "bin/meTypeset.py", line 253, in main
    me_typeset_instance.run()
  File "bin/meTypeset.py", line 245, in run
    self.run_modules()
  File "bin/meTypeset.py", line 152, in run_modules
    DocxToTei(self.gv).run(True, self.args['--proprietary'])
  File "/opt/meTypeset/bin/docxtotei.py", line 155, in run
    doc_prop = open(os.path.join(self.gv.docx_temp_folder_path, 'docProps', 'core.xml'), 'r+')
FileNotFoundError: [Errno 2] No such file or directory: '/data/output/docx/docProps/core.xml'
```

"output" folder is created, but there is no /docProps/core.xml file there (or anywhere in the output folder).

Any clue about what is happening? Am I doing something wrong?

Cheers,
m.

**Comment by de-code** [comment]
Hi @marcbria ,

apologies, I missed your issue.

`meTypeset` only works with Word or similar documents, not PDF.
A `docx` file is actually a zip file. You received the first error because the PDF file is not a zip file (unlike docx).
